"""create pokemons table"""

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('types', sa.String(length=120), nullable=True),
    sa.Column('sprite', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pokemons_external_id'), 'pokemons', ['external_id'], unique=False)
    op.create_index(op.f('ix_pokemons_id'), 'pokemons', ['id'], unique=False)
    op.create_index(op.f('ix_pokemons_name'), 'pokemons', ['name'], unique=True)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pokemons_name'), table_name='pokemons')
    op.drop_index(op.f('ix_pokemons_id'), table_name='pokemons')
    op.drop_index(op.f('ix_pokemons_external_id'), table_name='pokemons')
    op.drop_table('pokemons')
    # ### end Alembic commands ###
